// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.

#include "StandardEvent.h"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

static const char* _0RL_library_version = omniORB_4_1;



void
StandardEvent::StateChangeEventType::operator>>= (cdrStream &_n) const
{
  _n.marshalString(producerId,0);
  _n.marshalString(sourceId,0);
  stateChangeCategory >>= _n;
  stateChangeFrom >>= _n;
  stateChangeTo >>= _n;

}

void
StandardEvent::StateChangeEventType::operator<<= (cdrStream &_n)
{
  producerId = _n.unmarshalString(0);
  sourceId = _n.unmarshalString(0);
  (StateChangeCategoryType&)stateChangeCategory <<= _n;
  (StateChangeType&)stateChangeFrom <<= _n;
  (StateChangeType&)stateChangeTo <<= _n;

}

void
StandardEvent::DomainManagementObjectRemovedEventType::operator>>= (cdrStream &_n) const
{
  _n.marshalString(producerId,0);
  _n.marshalString(sourceId,0);
  _n.marshalString(sourceName,0);
  sourceCategory >>= _n;

}

void
StandardEvent::DomainManagementObjectRemovedEventType::operator<<= (cdrStream &_n)
{
  producerId = _n.unmarshalString(0);
  sourceId = _n.unmarshalString(0);
  sourceName = _n.unmarshalString(0);
  (SourceCategoryType&)sourceCategory <<= _n;

}

void
StandardEvent::DomainManagementObjectAddedEventType::operator>>= (cdrStream &_n) const
{
  _n.marshalString(producerId,0);
  _n.marshalString(sourceId,0);
  _n.marshalString(sourceName,0);
  sourceCategory >>= _n;
  ::CORBA::Object::_marshalObjRef(sourceIOR,_n);

}

void
StandardEvent::DomainManagementObjectAddedEventType::operator<<= (cdrStream &_n)
{
  producerId = _n.unmarshalString(0);
  sourceId = _n.unmarshalString(0);
  sourceName = _n.unmarshalString(0);
  (SourceCategoryType&)sourceCategory <<= _n;
  sourceIOR = ::CORBA::Object::_unmarshalObjRef(_n);

}

